stopwords = {
    'a', 'about', 'above', 'after', 'again', 'against', 'all', 'almost',
    'along', 'already', 'also', 'although', 'always', 'am', 'among', 'an',
    'and', 'another', 'any', 'anything', 'are', 'as', 'asked', 'associated',
    'at', 'away', 'back', 'based', 'be', 'because', 'becomes', 'been',
    'before', 'began', 'behind', 'being', 'below', 'better', 'between', 'both',
    'but', 'by', 'called', 'came', 'can', 'cannot', 'case', 'certain',
    'change', 'come', 'consider', 'could', 'day', 'death', 'did', 'different',
    'discussed', 'do', 'does', 'done', 'down', 'due', 'during', 'each',
    'either', 'enough', 'even', 'ever', 'every', 'expected', 'few', 'finally',
    'find', 'first', 'following', 'follows', 'for', 'from', 'further', 'gave',
    'general', 'get', 'give', 'given', 'gives', 'go', 'going', 'good', 'got',
    'great', 'had', 'has', 'have', 'having', 'he', 'hence', 'her', 'here',
    'herself', 'high', 'higher', 'him', 'himself', 'his', 'how', 'however',
    'i', 'if', 'ill', 'in', 'indeed', 'into', 'is', 'it', 'its', 'itself',
    'just', 'knew', 'know', 'known', 'large', 'larger', 'last', 'least',
    'less', 'let', 'life', 'like', 'little', 'long', 'look', 'looked', 'lower',
    'made', 'make', 'man', 'many', 'may', 'me', 'might', 'more', 'moreover',
    'most', 'much', 'must', 'my', 'myself', 'need', 'never', 'next', 'no',
    'nor', 'not', 'note', 'nothing', 'now', 'number', 'obtain', 'of', 'off',
    'often', 'old', 'on', 'once', 'one', 'only', 'or', 'other', 'others',
    'our', 'out', 'over', 'own', 'particular', 'perhaps', 'possible',
    'present', 'previous', 'quite', 'rather', 'respectively', 'result', 'said',
    'same', 'say', 'see', 'seemed', 'seen', 'several', 'shall', 'she',
    'should', 'show', 'shown', 'shows', 'similar', 'since', 'small', 'so',
    'some', 'something', 'soon', 'still', 'such', 'take', 'taken', 'tell',
    'than', 'that', 'the', 'thee', 'their', 'them', 'themselves', 'then',
    'there', 'therefore', 'these', 'they', 'thing', 'things', 'think', 'this',
    'those', 'thou', 'though', 'thought', 'through', 'thus', 'thy', 'till',
    'time', 'to', 'together', 'told', 'too', 'toward', 'two', 'under', 'until',
    'up', 'upon', 'us', 'use', 'used', 'using', 'very', 'want', 'was', 'way',
    'we', 'well', 'went', 'were', 'what', 'when', 'where', 'whether', 'which',
    'while', 'who', 'whom', 'whose', 'why', 'will', 'with', 'within',
    'without', 'work', 'would', 'yet', 'you', 'your'
}

mathstopwords = {
    'if', 'then', 'let', 'theorem', 'proposition', 'definition', 'lemma',
    'corollary', 'called', 'said', 'be', 'remark', 'denote', 'denoted',
    'given'
}
